#!/usr/bin/env python
#####################################
# Installation module for httprint
#####################################

# AUTHOR OF MODULE NAME
AUTHOR="Nathan Underwood (sainate)"

# DESCRIPTION OF THE MODULE
DESCRIPTION="This module will install/update HTTPrint - HTTP server fingerprinting tool"

# INSTALL TYPE GIT, SVN, FILE DOWNLOAD
# OPTIONS = GIT, SVN, FILE
INSTALL_TYPE="FILE"

# LOCATION OF THE FILE OR GIT/SVN REPOSITORY
REPOSITORY_LOCATION="http://www.net-square.com/_assets/httprint_linux_301.zip"

# WHERE DO YOU WANT TO INSTALL IT
INSTALL_LOCATION="httprint"

# DEPENDS FOR DEBIAN INSTALLS
DEBIAN="curl,unzip"

# DEPENDS FOR FEDORA INSTALLS
FEDORA="unzip,curl"

# THIS WILL STILL RUN AFTER COMMANDS EVEN IF ITS ALREADY INSTALLED. USEFUL FOR FILE UPDATES AND WHEN NOT USING GIT OR OTHER APPLICATIONS THAT NEEDS AFTER COMMANDS EACH TIME
BYPASS_UPDATE="YES"

# COMMANDS TO RUN AFTER
AFTER_COMMANDS="cd {INSTALL_LOCATION},unzip -j -o httprint_linux_301.zip"
# THIS WILL CREATE AN AUTOMATIC LAUNCHER FOR THE TOOL
LAUNCHER="httprint"

